name: 'run-test'
description: 'Compile and run a particular phantom test'

inputs:
  SETUP:
    description: 'SETUP to compile'
    required: true
    default: 'test'
  tests:
    description: 'The name of the test(s) to run'
    required: false
    default: ''
  SYSTEM:
    description: 'system/compiler to run on'
    required: false
    default: 'gfortran'
  DEBUG:
    description: 'whether to turn on debugging or not'
    required: false
    default: 'no'

runs:
  using: "composite"
  steps:
    - name: "compile"
      run: make SETUP=${{ inputs.SETUP }} DEBUG=${{ inputs.DEBUG }} phantomtest
      shell: bash
      env:
        SYSTEM: ${{ inputs.SYSTEM }}

    - name: "run testsuite"
      run: ./bin/phantomtest ${{ inputs.SETUP }}
      shell: bash
