name: 'run-test'
description: 'Compile and run a particular phantom test(s)'

inputs:
  SETUP:
    description: 'SETUP to compile'
    required: true
    default: 'test'
  SYSTEM:
    description: 'SYSTEM variable to use when compiling e.g. gfortran'
    required: false
    default: 'gfortran'
  DEBUG:
    description: 'whether to turn on debugging or not (yes/no)'
    required: false
    default: 'no'
  phantom_tests:
    description: 'List of phantom test names to run'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - name: "compile"
      run: make SETUP=${{ inputs.SETUP }} DEBUG=${{ inputs.DEBUG }} phantomtest
      shell: bash
      env:
        SYSTEM: ${{ inputs.SYSTEM }}

    - name: "run testsuite"
      run: ./bin/phantomtest ${{ inputs.phantom_tests }}
      shell: bash
