name: 'run-test'
description: 'Compile and run a particular phantom test'

inputs:
  SETUP:
    description: 'SETUP to compile'
    required: true
    default: 'test'
  tests:
    description: 'The name of the test(s) to run'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - name: "compile"
      run: make SETUP=${{ inputs.SETUP }} phantomtest
      working-directory: ${{ github.action_path }}
      shell: bash

    - name: "run testsuite"
      run: ./bin/phantomtest ${{ inputs.SETUP }}
      working-directory: ${{ github.action_path }}
      shell: bash
