name: 'compile-test'
description: 'Run a compile only test in the phantom repo'

inputs:
  SETUP:
    description: 'SETUP to compile'
    required: true
    default: 'test'
  target:
    description: 'Compile target'
    required: true
    default: 'phantomtest'
  SYSTEM:
    description: 'system/compiler to run on'
    required: false
    default: 'gfortran'
  DEBUG:
    description: 'whether to turn on debugging or not'
    required: false
    default: 'no'

runs:
  using: "composite"
  steps:
    - name: "compile"
      run: make SETUP=${{ inputs.SETUP }} DEBUG=${{ inputs.DEBUG }} ${{ inputs.target }}
      shell: bash
      env:
        SYSTEM: ${{ inputs.SYSTEM }}
