name: 'build-test'
description: 'Run a build-only test in the phantom repo'

inputs:
  SETUP:
    description: 'SETUP to compile'
    required: true
    default: 'test'
  SYSTEM:
    description: 'system/compiler to run on'
    required: false
    default: 'gfortran'
  DEBUG:
    description: 'whether to turn on debugging or not'
    required: false
    default: 'no'
  make_target:
    description: 'Build target in makefile'
    required: true
    default: 'phantomtest'

runs:
  using: "composite"
  steps:
    - name: "compile"
      run: make SETUP=${{ inputs.SETUP }} DEBUG=${{ inputs.DEBUG }} ${{ inputs.make_target }}
      shell: bash
      env:
        SYSTEM: ${{ inputs.SYSTEM }}
