name: bench-bot

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ bench-bot ]
  pull_request:
    branches: [ master ]

env:
  OMP_STACKSIZE: 512M
  WEB_USER: ec2-user
  WEB_SERVER: data.phantom.cloud.edu.au
  BENCH_LOG_DIR: /var/www/html/ci/bench/
  PERF_PLOT_DIR: /var/www/html/nightly/opt/

jobs:

  extract:
    runs-on: ubuntu-latest
    outputs:
      setups: ${{ steps.extract_step.outputs.setups }}

    steps:
      - name: "Checkout benchmarks repo for the directory names"
        uses: actions/checkout@v2
        with:
          repository: phantomSPH/phantom-benchmarks

      - name: "Extract setups from directory"
        id: extract_step
        run: echo ::set-output name=setups::$(printf '%s\n' */ | sort -r | sed 's:/$::' |jq -cnR '[inputs]')

  bench:
    needs: extract
    strategy:
      fail-fast: false
      matrix:
        setup: ${{fromJson(needs.extract.outputs.setups)}}

    runs-on: self-hosted

    steps:

    - name: "Nuke the github workspace before doing anything"
      run: rm -r ${{ github.workspace }} && mkdir ${{ github.workspace }}

    - name: "Install ansible"
      run: sudo apt-get --yes install ansible

    - name: "Clone phantom"
      uses: actions/checkout@v2
      with:
        ssh-known-hosts: |
          ${{ secrets.BITBUCKET_KNOWN_HOST }}
          ${{ secrets.WEBSERVER_KNOWN_HOST }}

    - name: "Grab a copy of the benchmark tests"
      uses: actions/checkout@v2
      with:
        repository: phantomSPH/phantom-benchmarks
        path: phantom-benchmarks
        lfs: true

    - name: "Get number of CPU cores"
      run: echo "::set-output name=count::$(nproc)"
      id: cpu

    - name: "Install SSH Key"
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.RUNNER_PRIVATE_KEY }}

    - name: "Load previous benchmark data from phantom-data-files"
      working-directory: phantom-benchmarks/${{ matrix.setup }}
      run: |
        rsync -vau ${WEB_USER}@${WEB_SERVER}:${BENCH_LOG_DIR}${{ matrix.setup }}/*.prev . || true
        rsync -vau ${WEB_USER}@${WEB_SERVER}:${BENCH_LOG_DIR}${{ matrix.setup }}/*.txt .  || true

    - name: "Run benchmarks"
      working-directory: phantom-benchmarks
      run: |
        ulimit -s unlimited
        systems="gfortran ifort"
        for SYSTEM in $systems; do
          echo ::group::SYSTEM=$SYSTEM
          SYSTEM=${SYSTEM} ./run-benchmarks.sh  ${{ matrix.setup }}
          echo ::endgroup::
        done
      env:
        OMP_NUM_THREADS: ${{ steps.cpu.outputs.count }}
        PHANTOM_DIR: ${{ github.workspace }}
        RETURN_ERR: "yes"

    - name: "Copy new benchmark data to phantom-data-files"
      working-directory: phantom-benchmarks/${{ matrix.setup }}
      run: |
        rsync -vau *.prev ${WEB_USER}@${WEB_SERVER}:${BENCH_LOG_DIR}${{ matrix.setup }}/
        rsync -vau *.txt  ${WEB_USER}@${WEB_SERVER}:${BENCH_LOG_DIR}${{ matrix.setup }}/

    - name: "Plot benchmarks"
      working-directory: phantom-benchmarks
      run: ./plot-benchmarks.sh
      env:
        PHANTOM_DIR: ${{ github.workspace }}

    - name: "Copy plots to phantom-data-files"
      working-directory: phantom-benchmarks
      run: |
        rsync -vau *.js              ${WEB_USER}@${WEB_SERVER}:${PERF_PLOT_DIR}
        rsync -vau performance.html  ${WEB_USER}@${WEB_SERVER}:${PERF_PLOT_DIR}
