name: bench-bot

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ bench-bot ]
  pull_request:
    branches: [ master ]

env:
  OMP_STACKSIZE: 512M

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        system:
          - ['self-hosted', 'ifort']
          - ['ubuntu-latest', 'gfortran']
        setup:
          - growth
          - tde

    runs-on: ${{ matrix.system[0] }}

    steps:

    - name: "Nuke the github workspace before doing anything"
      run: rm -r ${{ github.workspace }} && mkdir ${{ github.workspace }}

    - name: "Clone phantom"
      uses: actions/checkout@v2

    - name: "Grab a copy of the benchmark tests"
      uses: actions/checkout@v2
      with:
        repository: phantomSPH/phantom-benchmarks
        path: phantom-benchmarks
        lfs: true

    - name: "Checkout LFS objects"
      working-directory: phantom-benchmarks
      run: git lfs checkout

    - name: Get number of CPU cores
      run: echo "::set-output name=count::$(nproc)"
      id: cpu

    - name: "Run benchmarks"
      working-directory: phantom-benchmarks
      run: ./run-benchmarks.sh  ${{ matrix.setup }}
      env:
        SYSTEM: ${{ matrix.system[1] }}
        OMP_NUM_THREADS: ${{ steps.cpu.outputs.count }}
        PHANTOM_DIR: ${{ github.workspace }}
