name: build-bot

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  OMP_STACKSIZE: 512M
  SPLASH_DIR: ${{ github.workspace }}/splash

jobs:
  extract:
    runs-on: ubuntu-latest
    outputs:
      setups: ${{ steps.extract_step.outputs.setups }}
    steps:
      - uses: actions/checkout@v2
      - run: echo
      - id: extract_step
        run: echo "::set-output name=setups::`grep 'ifeq ($(SETUP)' ./build/Makefile | grep -v skip | cut -d, -f 2 | cut -d')' -f 1`"

  build:
    needs: extract
    strategy:
      fail-fast: false
      matrix:
        system:
          - ['self-hosted', 'ifort']
          - ['ubuntu-latest', 'gfortran']
        debug:
          - no
          - yes
        input: # [SETUP, make_target]
          - ['blob', 'phantomtest']
          - ['test', 'utils']

    runs-on: ${{ matrix.system[0] }}

    steps:

    - run: echo ${{needs.extract.outputs.setups}}
    - run: "false"

    - name: "Nuke the github workspace before doing anything"
      run: rm -r ${{ github.workspace }} && mkdir ${{ github.workspace }}

    - name: "Clone phantom"
      uses: actions/checkout@v2

    - name: "Grab a copy of splash source code"
      uses: actions/checkout@v2
      with:
        repository: danieljprice/splash
        path: splash

    - name: "Compile phantom"
      run: make SETUP=${{ matrix.input[0] }} DEBUG=${{ matrix.debug }} ${{ matrix.input[1] }}
      env:
        SYSTEM: ${{ matrix.system[1] }}
