name: build-bot

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ build-bot ]
  pull_request:
    branches: [ master ]

env:
  OMP_STACKSIZE: 512M
  SPLASH_DIR: ${{ github.workspace }}/splash
  PHANTOM_DIR: ${{ github.workspace }}

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        system:
          - ['self-hosted', 'ifort']
          - ['ubuntu-latest', 'gfortran']
        debug:
          - no
          - yes

    runs-on: ${{ matrix.system[0] }}

    steps:

    - name: "Nuke the github workspace before doing anything"
      run: rm -r ${{ github.workspace }} && mkdir ${{ github.workspace }}

    - name: "Clone phantom"
      uses: actions/checkout@v2

    - name: "Grab a copy of splash source code"
      uses: actions/checkout@v2
      with:
        repository: danieljprice/splash
        path: splash

    - name: "Run buildbot.sh"
      run: ./builbot.sh 17000000
      working-directory: scripts
      env:
        SYSTEM: ${{ matrix.system[1] }}
