name: build-bot

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "0 0 * * *"

env:
  # Only post results to web server if secrets are accessible (i.e. scheduled runs)
  SECRET_ACCESS: ${{ secrets.RUNNER_PRIVATE_KEY  != '' }}
  OMP_STACKSIZE: 512M
  SPLASH_DIR: ${{ github.workspace }}/splash
  PHANTOM_DIR: ${{ github.workspace }}
  WEB_USER: ec2-user
  WEB_SERVER: data.phantom.cloud.edu.au
  WEB_HTML_DIR: /var/www/html
  BUILD_LOG_DIR: /ci/build/logs
  RSYNC_RSH: ssh -o "StrictHostKeyChecking=no" -o "UserKnownHostsFile=/dev/null"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        system:
          - ['self-hosted', 'ifort']
          - ['ubuntu-latest', 'gfortran']

    runs-on: ${{ matrix.system[0] }}

    steps:

    - name: "Install SSH Key"
      if: ${{ env.SECRET_ACCESS == 'true' }}
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.RUNNER_PRIVATE_KEY }}

    - name: "Nuke the github workspace before doing anything"
      run: rm -r ${{ github.workspace }} && mkdir ${{ github.workspace }}

    - name: "Clone phantom"
      uses: actions/checkout@v2

    - name: "Grab a copy of splash source code"
      uses: actions/checkout@v2
      with:
        repository: danieljprice/splash
        path: splash

    - name: "Create logs directory"
      run: mkdir logs

    - name: "Grab previous build logs from web server"
      env:
        WGET: wget --recursive --no-parent --reject "index.html*" --cut-dirs=2 --no-host-directories
      run: ${WGET} -A '*${{ matrix.system[1] }}.txt' http://${WEB_SERVER}${BUILD_LOG_DIR}/ || true

    - name: "Run buildbot.sh"
      run: ./buildbot.sh 17000000 http://${WEB_SERVER}/${BUILD_LOG_DIR}
      working-directory: scripts
      env:
        SYSTEM: ${{ matrix.system[1] }}
        RETURN_ERR: yes

    - name: "Copy new build logs to web server"
      if: always() && env.SECRET_ACCESS
      run: rsync -vau logs/*.txt ${WEB_USER}@${WEB_SERVER}:${WEB_HTML_DIR}/${BUILD_LOG_DIR}

    - name: "Copy HTML files to web server"
      if: always() && env.SECRET_ACCESS
      run: |
        export WEB_BUILD_DIR=${WEB_HTML_DIR}/nightly/build/$(date "+%Y%m%d")
        ssh -o "StrictHostKeyChecking=no" -o "UserKnownHostsFile=/dev/null" ${WEB_USER}@${WEB_SERVER} -- mkdir -p ${WEB_BUILD_DIR}
        rsync -vau logs/*.html ${WEB_USER}@${WEB_SERVER}:${WEB_BUILD_DIR}/

    - name: logs/build-failures-${{ matrix.system[1] }}.txt
      if: always()
      run: cat logs/build-failures-${{ matrix.system[1] }}.txt || true

    - name: logs/setup-failures-${{ matrix.system[1] }}.txt
      if: always()
      run: cat logs/setup-failures-${{ matrix.system[1] }}.txt || true

    - name: logs/make-*-${{ matrix.system[1] }}.txt
      if: always()
      run: |
        echo
        for item in $(ls logs/make-*-${{ matrix.system[1] }}.txt); do
          echo ::group::"${item}"
          cat $item
          echo ::endgroup::
        done
