# This is a basic workflow to help you get started with Actions
name: mpi

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  # push:
  #   branches: [ master ]
  # pull_request:
  #   branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      SYSTEM: gfortran
      OMP_STACKSIZE: 512M

    steps:
    - name: Install gfortran and openMPI
      run: sudo apt-get --yes install gfortran openmpi-bin openmpi-common libopenmpi-dev

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: compile with MPI
      run: make SETUP=testkd MPI=yes OPENMP=no phantomtest

    - name: test with MPI
      run: mpirun --allow-run-as-root -np 2 ./bin/phantomtest
