# This is a basic workflow to help you get started with Actions
name: mpi

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ mpi ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        system:
          - ['self-hosted', 'ifort']
          - ['ubuntu-latest', 'gfortran']
        debug:
          - no
          - yes
        openmp:
          - no
          - yes

    name: MPI SYSTEM=${{ matrix.system[1] }} DEBUG=${{ matrix.debug }} OPENMP=${{ matrix.openmp }}

    runs-on: ${{ matrix.system[0] }}

    env:
      OMP_STACKSIZE: 512M

    steps:

    - name: Install gfortran and openMPI
      run: |
        sudo apt-get update
        sudo apt-get --yes install gfortran openmpi-bin openmpi-common libopenmpi-dev

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Compile with MPI
      run: make SETUP=testkd MPI=yes OPENMP=${{ matrix.openmp }}  phantomtest
      env:
        SYSTEM: ${{ matrix.system[1] }}

    - name: Test with MPI
      run: mpirun --allow-run-as-root -np 2 ./bin/phantomtest
